CREATE TABLE "sana_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sana_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "sana_user" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sana_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"clerkUserId" varchar(191) NOT NULL,
	"role" varchar(20) DEFAULT 'viewer' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "sana_user_clerkUserId_unique" UNIQUE("clerkUserId")
);
--> statement-breakpoint
CREATE INDEX "name_idx" ON "sana_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "user_clerk_id_idx" ON "sana_user" USING btree ("clerkUserId");